### ISSUE TITLE
请求提供许可/引用信息

### ISSUE THREAD

**Issue by Rratic** [SAST-skill-docers/sast-skill-docs#33]
如题，希望能够在[文档](https://github.com/JuliaRoadmap/zh)中引用本项目的内容，若许可无法适配，将采用外部链接

**Comment by c7w** [comment]
Glad to hear that! We always appreciate the chance to expand our influence :)
Could you please list the content you want to ref in detail so that we can get in contact with the corresponding editors?
The copyright is default to be reserved by the editors themselves.

By the way, recently we shall talk about the LICENSE of our whole project with all editors. Thanks for your reminder!

**Comment by c7w** [comment]
Then that's okay as long as u mention the site of our docs and not claiming yourself as the author of the docs.
Non-commercial usage is also advocated.

In fact, we are strongly in support of your contribution to the community :)
